baseURL: 'https://club-venom.com'
languageCode: en-us
disableKinds:
  - '404'
title: 'Club Venom Wrestling'
markup:
  goldmark:
    renderer:
      unsafe: true
permalinks:
  post: '/post/:year/:month/:day/:slug/'
  note: '/note/:year/:month/:day/:slug/'
menus:
  main:
    - name: Registration
      Url: /registration
      weight: 1
    # - name: Teams
    #   Url: /teams
    #   weight: 2
    # - name: Gear Shop
    #   Url: /gearshop
    #   weight: 3
    # - name: Sponsorship
    #   Url: /sponsorship
    #   weight: 4
    # - name: About
    #   Url: /about
    #   weight: 5
    - name: Training
      Url: /training
      weight: 2
    - name: FAQ
      Url: /faq
      weight: 3
    - name: Contact
      Url: /contact
      weight: 4
outputs:
  posts:
    - HTML
    - RSS
params:
  author: 'Club Venom'
  footer:
    firstcolumn:
    secondcolumn:
    thirdcolumn:
      - Copyright 2025 Club Venom. All Rights Reserved.
